camunda:
  sso:
    admin-user-id: 116915761348654177223
  bpm:
    admin-user:
      id: demo
      password: demo

    filter:
      create: All tasks
    authorization:
      enabled: true

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: 'jdbc:h2:file:./camunda-h2-database'
    username: sa
    password: sa

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "832780395862-sk6knpak6t0uln900d8671tiib0vt008.apps.googleusercontent.com"
            clientSecret: "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"
            scope:
              - email
              - profile
server:
  port: 8080

